package gg.umbra.mapping;

import gg.umbra.Umbra;
import gg.umbra.mapping.mappings.MAbstractBlockProperties;
import gg.umbra.mapping.mappings.MAbstractBlockState;
import gg.umbra.mapping.mappings.MAbstractClientPlayer;
import gg.umbra.mapping.mappings.MAbstractClientPlayerBridge;
import gg.umbra.mapping.mappings.MAbstractGui;
import gg.umbra.mapping.mappings.MActiveRenderInfo;
import gg.umbra.mapping.mappings.MArmorMaterial;
import gg.umbra.mapping.mappings.MAtomicReferenceArrayBridge;
import gg.umbra.mapping.mappings.MAttributeModifier;
import gg.umbra.mapping.mappings.MAxisAlignedBB;
import gg.umbra.mapping.mappings.MBiome;
import gg.umbra.mapping.mappings.MBiomeProviderBridge;
import gg.umbra.mapping.mappings.MBiomeRegistryName;
import gg.umbra.mapping.mappings.MBiomeRegistrySwitch;
import gg.umbra.mapping.mappings.MBlock;
import gg.umbra.mapping.mappings.MBlockBed;
import gg.umbra.mapping.mappings.MBlockHorizontal;
import gg.umbra.mapping.mappings.MBlockLayerOverrideFallbackHook;
import gg.umbra.mapping.mappings.MBlockModelRenderer;
import gg.umbra.mapping.mappings.MBlockPos;
import gg.umbra.mapping.mappings.MTickingBlockEntity;
import gg.umbra.mapping.mappings.MBlockRayTraceResult;
import gg.umbra.mapping.mappings.MBlockReader;
import gg.umbra.mapping.mappings.MBlockReaderBridge;
import gg.umbra.mapping.mappings.MGpuTextureView;
import gg.umbra.mapping.mappings.MBlockStateContainerBridge;
import gg.umbra.mapping.mappings.MBlockStateWorldBridge;
import gg.umbra.mapping.mappings.MBlocks;
import gg.umbra.mapping.mappings.MBuiltInRegistries;
import gg.umbra.mapping.mappings.MBytePacketFieldBridge;
import gg.umbra.mapping.mappings.MC03PacketPlayerBridge;
import gg.umbra.mapping.mappings.MC0BPacketEntityAction_Action;
import gg.umbra.mapping.mappings.MCPacketAnimation;
import gg.umbra.mapping.mappings.MCPacketChatMessage;
import gg.umbra.mapping.mappings.MCPacketEntityAction;
import gg.umbra.mapping.mappings.MCPacketHeldItemChange;
import gg.umbra.mapping.mappings.MCPacketPlayer;
import gg.umbra.mapping.mappings.MCPacketPlayerBlockPlacement;
import gg.umbra.mapping.mappings.MCPacketPlayerDigging;
import gg.umbra.mapping.mappings.MCPacketPlayer_Position;
import gg.umbra.mapping.mappings.MCPacketPlayer_PositionRotation;
import gg.umbra.mapping.mappings.MCPacketPlayer_Rotation;
import gg.umbra.mapping.mappings.MCPacketUseEntity;
import gg.umbra.mapping.mappings.MCPacketUseEntityAction;
import gg.umbra.mapping.mappings.MCPacketUseEntityActionPacket;
import gg.umbra.mapping.mappings.MCPacketUseEntityOne;
import gg.umbra.mapping.mappings.MCPacketUseEntityPacket;
import gg.umbra.mapping.mappings.MCaughtEntityActionBridge;
import gg.umbra.mapping.mappings.MChannel;
import gg.umbra.mapping.mappings.MChatMessageRenderTarget;
import gg.umbra.mapping.mappings.MChestType;
import gg.umbra.mapping.mappings.MChestTypeHolder;
import gg.umbra.mapping.mappings.MChunk;
import gg.umbra.mapping.mappings.MChunkSection;
import gg.umbra.mapping.mappings.MClickType;
import gg.umbra.mapping.mappings.MClientChatReceivedEvent;
import gg.umbra.mapping.mappings.MClientChunkProvider;
import gg.umbra.mapping.mappings.MContainer;
import gg.umbra.mapping.mappings.MDamageSource;
import gg.umbra.mapping.mappings.MDamageSources;
import gg.umbra.mapping.mappings.MDataComponentMap;
import gg.umbra.mapping.mappings.MDataComponents;
import gg.umbra.mapping.mappings.MDefaultVertexFormats;
import gg.umbra.mapping.mappings.MDeltaTracker;
import gg.umbra.mapping.mappings.MDirection;
import gg.umbra.mapping.mappings.MDirectionAxis;
import gg.umbra.mapping.mappings.MDirectionBridge;
import gg.umbra.mapping.mappings.MDirectionVector;
import gg.umbra.mapping.mappings.MEffectRenderer;
import gg.umbra.mapping.mappings.MEmptyDataComponentMap;
import gg.umbra.mapping.mappings.MEmptyItemAttributeModifiers;
import gg.umbra.mapping.mappings.MEnchantment;
import gg.umbra.mapping.mappings.MEnchantmentHelper;
import gg.umbra.mapping.mappings.MEnchantmentHelperBridge;
import gg.umbra.mapping.mappings.MEnchantmentModifierDamage;
import gg.umbra.mapping.mappings.MEnchantments;
import gg.umbra.mapping.mappings.MEnderPearlProjectileBridge;
import gg.umbra.mapping.mappings.MEntity;
import gg.umbra.mapping.mappings.MEntityArrow;
import gg.umbra.mapping.mappings.MEntityClientPlayerMP;
import gg.umbra.mapping.mappings.MEntityEnderPearl;
import gg.umbra.mapping.mappings.MEntityEquipmentSlot;
import gg.umbra.mapping.mappings.MEntityEquipmentSlotHolder;
import gg.umbra.mapping.mappings.MEntityFX;
import gg.umbra.mapping.mappings.MEntityFishHook;
import gg.umbra.mapping.mappings.MEntityItem;
import gg.umbra.mapping.mappings.MEntityLiving;
import gg.umbra.mapping.mappings.MEntityLivingBase;
import gg.umbra.mapping.mappings.MEntityOtherPlayerMP;
import gg.umbra.mapping.mappings.MEntityPlayer;
import gg.umbra.mapping.mappings.MEntityPlayerMacroBridge;
import gg.umbra.mapping.mappings.MEntityPlayerSP;
import gg.umbra.mapping.mappings.MEntityPotion;
import gg.umbra.mapping.mappings.MEntityRayTraceBridge;
import gg.umbra.mapping.mappings.MEntityRayTraceResult;
import gg.umbra.mapping.mappings.MEntityRemovalReason;
import gg.umbra.mapping.mappings.MEntityRenderer;
import gg.umbra.mapping.mappings.MFogRenderer;
import gg.umbra.mapping.mappings.MEntitySelectors;
import gg.umbra.mapping.mappings.MEntitySize;
import gg.umbra.mapping.mappings.MEnumActionResult;
import gg.umbra.mapping.mappings.MEnumCreatureAttribute;
import gg.umbra.mapping.mappings.MEnumCreatureAttributeBridge;
import gg.umbra.mapping.mappings.MEnumFacing;
import gg.umbra.mapping.mappings.MEnumHand;
import gg.umbra.mapping.mappings.MEnumHandBridge;
import gg.umbra.mapping.mappings.MEnumParticleTypes;
import gg.umbra.mapping.mappings.MEnumWorldBlockLayer;
import gg.umbra.mapping.mappings.MEquipmentSlotSet;
import gg.umbra.mapping.mappings.MEquippable;
import gg.umbra.mapping.mappings.MEvent;
import gg.umbra.mapping.mappings.MWorldProvider;
import gg.umbra.mapping.mappings.MFontGlyph;
import gg.umbra.mapping.mappings.MFontGlyphInfo;
import gg.umbra.mapping.mappings.MFontManager;
import gg.umbra.mapping.mappings.MFontRenderer;
import gg.umbra.mapping.mappings.MFontSet;
import gg.umbra.mapping.mappings.MFoodProperties;
import gg.umbra.mapping.mappings.MFoodStats;
import gg.umbra.mapping.mappings.MFoods;
import gg.umbra.mapping.mappings.MFramebuffer;
import gg.umbra.mapping.mappings.MFreecamMovementInputBridge;
import gg.umbra.mapping.mappings.MFreecamPlayerBridge;
import gg.umbra.mapping.mappings.MGL11;
import gg.umbra.mapping.mappings.MGL20;
import gg.umbra.mapping.mappings.MGameProfile;
import gg.umbra.mapping.mappings.MGameSettings;
import gg.umbra.mapping.mappings.MGameSettingsGuiScale;
import gg.umbra.mapping.mappings.MGameSettingsGuiScaleValue;
import gg.umbra.mapping.mappings.MGameSettingsValue;
import gg.umbra.mapping.mappings.MGlStateManager;
import gg.umbra.mapping.mappings.MGlStateManagerFogStateBridge;
import gg.umbra.mapping.mappings.MGlStateManagerFogStateObject;
import gg.umbra.mapping.mappings.MGlStateManagerTexGenCoord;
import gg.umbra.mapping.mappings.MGlStateManagerTexGenState;
import gg.umbra.mapping.mappings.MGlStateManager_BlendState;
import gg.umbra.mapping.mappings.MGlStateManager_FogState;
import gg.umbra.mapping.mappings.MGlStateManager_TextureState;
import gg.umbra.mapping.mappings.MGlyphInfo;
import gg.umbra.mapping.mappings.MGlyphProvider;
import gg.umbra.mapping.mappings.MGuiChat;
import gg.umbra.mapping.mappings.MGuiChest;
import gg.umbra.mapping.mappings.MGuiContainer;
import gg.umbra.mapping.mappings.MGuiContainerCreativeSlot;
import gg.umbra.mapping.mappings.MGuiInventory;
import gg.umbra.mapping.mappings.MGuiPlayerTabOverlay;
import gg.umbra.mapping.mappings.MGuiScreen;
import gg.umbra.mapping.mappings.MGuiSpriteManager;
import gg.umbra.mapping.mappings.MHolder;
import gg.umbra.mapping.mappings.MI18n;
import gg.umbra.mapping.mappings.MIAttributeInstance;
import gg.umbra.mapping.mappings.MIBlockState;
import gg.umbra.mapping.mappings.MIChunkProvider;
import gg.umbra.mapping.mappings.MIInventory;
import gg.umbra.mapping.mappings.MISelectionContext;
import gg.umbra.mapping.mappings.MITextComponent;
import gg.umbra.mapping.mappings.MITooltipFlag;
import gg.umbra.mapping.mappings.MITooltipFlagBridge;
import gg.umbra.mapping.mappings.MIWorldNameable;
import gg.umbra.mapping.mappings.MInputMappings;
import gg.umbra.mapping.mappings.MInputMappingsBridge;
import gg.umbra.mapping.mappings.MInputMappingsInput;
import gg.umbra.mapping.mappings.MInventoryListBridge;
import gg.umbra.mapping.mappings.MInventoryPlayer;
import gg.umbra.mapping.mappings.MItem;
import gg.umbra.mapping.mappings.MItemActionResult;
import gg.umbra.mapping.mappings.MItemArmor;
import gg.umbra.mapping.mappings.MItemAttributeModifiers;
import gg.umbra.mapping.mappings.MItemAttributeModifiersComponent;
import gg.umbra.mapping.mappings.MItemAttributeModifiersComponent$Entry;
import gg.umbra.mapping.mappings.MItemBlock;
import gg.umbra.mapping.mappings.MItemBlockBridge;
import gg.umbra.mapping.mappings.MItemCameraTransformBaseBridge;
import gg.umbra.mapping.mappings.MItemCameraTransformIntermediateBridge;
import gg.umbra.mapping.mappings.MItemCameraTransformLeafBridge;
import gg.umbra.mapping.mappings.MItemCameraTransformType;
import gg.umbra.mapping.mappings.MItemPotion;
import gg.umbra.mapping.mappings.MItemRenderContext;
import gg.umbra.mapping.mappings.MItemRenderer;
import gg.umbra.mapping.mappings.MItemRendererBridge;
import gg.umbra.mapping.mappings.MItemStack;
import gg.umbra.mapping.mappings.MItemSword;
import gg.umbra.mapping.mappings.MItemTool;
import gg.umbra.mapping.mappings.MItem_ToolMaterial;
import gg.umbra.mapping.mappings.MItems;
import gg.umbra.mapping.mappings.MKeyBinding;
import gg.umbra.mapping.mappings.MKeyboardHandler;
import gg.umbra.mapping.mappings.MLanguage;
import gg.umbra.mapping.mappings.MLanguageStateBridge;
import gg.umbra.mapping.mappings.MLaunchClassLoader;
import gg.umbra.mapping.mappings.MLegacyEntityRenderPreHook;
import gg.umbra.mapping.mappings.MLightTexture;
import gg.umbra.mapping.mappings.MLists;
import gg.umbra.mapping.mappings.MMLGBlockWrapper;
import gg.umbra.mapping.mappings.MMainWindow;
import gg.umbra.mapping.mappings.MMappedClassSlotFp;
import gg.umbra.mapping.mappings.MMappedClassSlotNRegistration;
import gg.umbra.mapping.mappings.MMappedClassSlotZG;
import gg.umbra.mapping.mappings.MMappedFieldSingletonWrapper;
import gg.umbra.mapping.mappings.MMaterial;
import gg.umbra.mapping.mappings.MMatrix4f;
import gg.umbra.mapping.mappings.MMatrix4fHandle;
import gg.umbra.mapping.mappings.MMatrix4fTransformVariantBridge;
import gg.umbra.mapping.mappings.MMatrixStack;
import gg.umbra.mapping.mappings.MMatrixStackEntry;
import gg.umbra.mapping.mappings.MMethodSlotZYBridge;
import gg.umbra.mapping.mappings.MMinecraft;
import gg.umbra.mapping.mappings.MBoundTickingBlockEntity;
import gg.umbra.mapping.mappings.MMobSpawnerBaseLogic;
import gg.umbra.mapping.mappings.MModelBiped;
import gg.umbra.mapping.mappings.MModelManager;
import gg.umbra.mapping.mappings.MModelPlayer;
import gg.umbra.mapping.mappings.MModelRenderer;
import gg.umbra.mapping.mappings.MMouseEvent;
import gg.umbra.mapping.mappings.MMouseHelper;
import gg.umbra.mapping.mappings.MMovementInput;
import gg.umbra.mapping.mappings.MMoverType;
import gg.umbra.mapping.mappings.MMutableBoundingBox;
import gg.umbra.mapping.mappings.MMutableTextComponent;
import gg.umbra.mapping.mappings.MNBTTagCompound;
import gg.umbra.mapping.mappings.MNBTTagList;
import gg.umbra.mapping.mappings.MNetHandlerPlayClient;
import gg.umbra.mapping.mappings.MNetHandlerPlayClientImpl;
import gg.umbra.mapping.mappings.MNetworkManager;
import gg.umbra.mapping.mappings.MNetworkManager_InboundHandlerTuplePacketListener;
import gg.umbra.mapping.mappings.MNetworkPlayerInfo;
import gg.umbra.mapping.mappings.MNonNullList;
import gg.umbra.mapping.mappings.MOpenedChestTypeSentinelBridge;
import gg.umbra.mapping.mappings.MOrdering;
import gg.umbra.mapping.mappings.MPacket;
import gg.umbra.mapping.mappings.MPacketIdFactory;
import gg.umbra.mapping.mappings.MPacketVelocityBridge;
import gg.umbra.mapping.mappings.MPlaySoundAtEntityEvent;
import gg.umbra.mapping.mappings.MPlayerControllerMP;
import gg.umbra.mapping.mappings.MPlayerDiggingAction;
import gg.umbra.mapping.mappings.MPlayerEvent_NameFormat;
import gg.umbra.mapping.mappings.MPlayerInfo;
import gg.umbra.mapping.mappings.MPlayerInput;
import gg.umbra.mapping.mappings.MPlayerInteractEvent;
import gg.umbra.mapping.mappings.MPlayerModel;
import gg.umbra.mapping.mappings.MPlayerSkin;
import gg.umbra.mapping.mappings.MPointOfView;
import gg.umbra.mapping.mappings.MPositionMoveRotation;
import gg.umbra.mapping.mappings.MPotion;
import gg.umbra.mapping.mappings.MPotionEffect;
import gg.umbra.mapping.mappings.MPotionVersionRange;
import gg.umbra.mapping.mappings.MQuaternion;
import gg.umbra.mapping.mappings.MRayTraceContext;
import gg.umbra.mapping.mappings.MRayTraceContext_BlockMode;
import gg.umbra.mapping.mappings.MRayTraceContext_FluidMode;
import gg.umbra.mapping.mappings.MRayTraceResult;
import gg.umbra.mapping.mappings.MRayTraceResult_Type;
import gg.umbra.mapping.mappings.MRegistry;
import gg.umbra.mapping.mappings.MRegistryAccess;
import gg.umbra.mapping.mappings.MRegistryAccessBridge;
import gg.umbra.mapping.mappings.MRegistryLookup;
import gg.umbra.mapping.mappings.MRegistryNamespaced;
import gg.umbra.mapping.mappings.MRegistrySimple;
import gg.umbra.mapping.mappings.MRegistryValueBridge;
import gg.umbra.mapping.mappings.MRender;
import gg.umbra.mapping.mappings.MRenderBatchFlushTarget;
import gg.umbra.mapping.mappings.MRenderBlocks;
import gg.umbra.mapping.mappings.MRenderBufferBridge;
import gg.umbra.mapping.mappings.MRenderGameOverlayEvent;
import gg.umbra.mapping.mappings.MRenderGlobal;
import gg.umbra.mapping.mappings.MRenderHelper;
import gg.umbra.mapping.mappings.MRenderItem;
import gg.umbra.mapping.mappings.MRenderItemContext;
import gg.umbra.mapping.mappings.MRenderLivingBase;
import gg.umbra.mapping.mappings.MRenderManager;
import gg.umbra.mapping.mappings.MRenderPlayer;
import gg.umbra.mapping.mappings.MRenderStateBridge;
import gg.umbra.mapping.mappings.MRenderStateBridgeVariant;
import gg.umbra.mapping.mappings.MRenderStateBuilder;
import gg.umbra.mapping.mappings.MRenderSystem;
import gg.umbra.mapping.mappings.MRenderTypeBuffer;
import gg.umbra.mapping.mappings.MRenderTypeBufferBridge;
import gg.umbra.mapping.mappings.MRenderWorldLastEvent;
import gg.umbra.mapping.mappings.MResourceKey;
import gg.umbra.mapping.mappings.MResourceKeyEnchantmentBridge;
import gg.umbra.mapping.mappings.MResourceKeyHolder;
import gg.umbra.mapping.mappings.MResourceKeyRegistryLookup;
import gg.umbra.mapping.mappings.MResourceKeyRegistryLookupStreamBridge;
import gg.umbra.mapping.mappings.MResourceLocation;
import gg.umbra.mapping.mappings.MResourceLocationConstantsBridge;
import gg.umbra.mapping.mappings.MResourceLocationKey;
import gg.umbra.mapping.mappings.MResourceLocationName;
import gg.umbra.mapping.mappings.MResourceManager;
import gg.umbra.mapping.mappings.MS08PacketPlayerPosLook;
import gg.umbra.mapping.mappings.MSEntityPacket;
import gg.umbra.mapping.mappings.MSPacketAnimation;
import gg.umbra.mapping.mappings.MSPacketBlockChange;
import gg.umbra.mapping.mappings.MSPacketChunkData;
import gg.umbra.mapping.mappings.MSPacketChunkDataExtracted;
import gg.umbra.mapping.mappings.MSPacketDestroyEntities;
import gg.umbra.mapping.mappings.MSPacketDestroyEntitiesArrayBridge;
import gg.umbra.mapping.mappings.MSPacketEntity;
import gg.umbra.mapping.mappings.MSPacketEntityStatus;
import gg.umbra.mapping.mappings.MSPacketEntityTeleport;
import gg.umbra.mapping.mappings.MSPacketEntityVelocity;
import gg.umbra.mapping.mappings.MSPacketExplosion;
import gg.umbra.mapping.mappings.MSPacketHeldItemChange;
import gg.umbra.mapping.mappings.MSPacketMapChunkBulk;
import gg.umbra.mapping.mappings.MSPacketMapChunkBulkBridge;
import gg.umbra.mapping.mappings.MSPacketPlayerPosLook;
import gg.umbra.mapping.mappings.MSPacketSoundEffect;
import gg.umbra.mapping.mappings.MSPacketSoundEffectBridge;
import gg.umbra.mapping.mappings.MScore;
import gg.umbra.mapping.mappings.MScoreObjective;
import gg.umbra.mapping.mappings.MScorePlayerTeam;
import gg.umbra.mapping.mappings.MScoreboard;
import gg.umbra.mapping.mappings.MScreen;
import gg.umbra.mapping.mappings.MServerData;
import gg.umbra.mapping.mappings.MSession;
import gg.umbra.mapping.mappings.MSetVisibility;
import gg.umbra.mapping.mappings.MShaderGroup;
import gg.umbra.mapping.mappings.MSharedMonsterAttributes;
import gg.umbra.mapping.mappings.MSharedMonsterAttributesBridge;
import gg.umbra.mapping.mappings.MSharedMonsterAttributesVariantBridge;
import gg.umbra.mapping.mappings.MShortPacketFieldBridge;
import gg.umbra.mapping.mappings.MSlot;
import gg.umbra.mapping.mappings.MSoundAwareEntityFX;
import gg.umbra.mapping.mappings.MSoundEvent;
import gg.umbra.mapping.mappings.MSoundEventRegistryName;
import gg.umbra.mapping.mappings.MStatusEffect;
import gg.umbra.mapping.mappings.MStatusEffectSpriteUploader;
import gg.umbra.mapping.mappings.MStringTextComponent;
import gg.umbra.mapping.mappings.MStringTextComponentBridge;
import gg.umbra.mapping.mappings.MStyle;
import gg.umbra.mapping.mappings.MTeam;
import gg.umbra.mapping.mappings.MTessellator;
import gg.umbra.mapping.mappings.MTextComponent;
import gg.umbra.mapping.mappings.MTextComponentBaseBridge;
import gg.umbra.mapping.mappings.MTextComponentString;
import gg.umbra.mapping.mappings.MTextComponentTranslation;
import gg.umbra.mapping.mappings.MTextComponentTranslationBridge;
import gg.umbra.mapping.mappings.MTextFormatting;
import gg.umbra.mapping.mappings.MTextureAtlasSprite;
import gg.umbra.mapping.mappings.MTextureAtlasSpriteInfo;
import gg.umbra.mapping.mappings.MTextureAtlasSpriteInfoBridge;
import gg.umbra.mapping.mappings.MTextureManager;
import gg.umbra.mapping.mappings.MTextureManagerHandle;
import gg.umbra.mapping.mappings.MTextureObject;
import gg.umbra.mapping.mappings.MTextureObjectHandle;
import gg.umbra.mapping.mappings.MTickEventPhase;
import gg.umbra.mapping.mappings.MFogType;
import gg.umbra.mapping.mappings.MTileEntity;
import gg.umbra.mapping.mappings.MTileEntityChest;
import gg.umbra.mapping.mappings.MItemFood;
import gg.umbra.mapping.mappings.MTileEntityMobSpawner;
import gg.umbra.mapping.mappings.MTimer;
import gg.umbra.mapping.mappings.MTitledScreen;
import gg.umbra.mapping.mappings.MTrajectoriesItemBridge;
import gg.umbra.mapping.mappings.MUtil;
import gg.umbra.mapping.mappings.MVec3I;
import gg.umbra.mapping.mappings.MVec3d;
import gg.umbra.mapping.mappings.MVector3f;
import gg.umbra.mapping.mappings.MObjectToIntMapEntry;
import gg.umbra.mapping.mappings.MVisGraph;
import gg.umbra.mapping.mappings.MVoxelShape;
import gg.umbra.mapping.mappings.MVoxelShapeBridge;
import gg.umbra.mapping.mappings.MWorld;
import gg.umbra.mapping.mappings.MWorldClient;
import gg.umbra.mapping.mappings.MClientWorldInfo;
import gg.umbra.mapping.mappings.MLevelEntityGetter;
import gg.umbra.mapping.mappings.MWorldInfo;
import gg.umbra.mapping.mappings.MWorldRenderer;
import gg.umbra.mapping.mappings.MSessionType;
import gg.umbra.ui.click.component.GuiComponent;
import gg.umbra.utils.render.GuiRenderPrimitives;
import gg.umbra.wrapper.impl.ForgeVersion;
import java.util.ArrayList;
import java.util.List;

public class Mapper {
    public MDirectionAxis directionAxis;
    public MResourceKeyRegistryLookupStreamBridge R2;
    public MWorldRenderer qZ;
    public MTextureManagerHandle renderTarget;
    public MTickEventPhase R8;
    public MGuiContainerCreativeSlot guiContainerCreativeSlot;
    public MBlockModelRenderer hE;
    public MEntityEquipmentSlot CY;
    public MRayTraceContext_FluidMode rayTraceFluidMode;
    public MSPacketPlayerPosLook Ry;
    public MDataComponentMap qk;
    public MCPacketHeldItemChange Ck;
    public MGuiChest guiChest;
    private static int DH;
    public MMouseHelper qI;
    public MBlockStateWorldBridge hu;
    public MWorld Cy;
    public MPlayerControllerMP hj;
    public MLists lists;
    public MEntityEquipmentSlotHolder hh;
    public MGlStateManager_BlendState glBlendState;
    public MBlockBed Dj;
    public MWorldClient ha;
    public MEntityRemovalReason h;
    public MRenderItemContext A;
    public MGlStateManager Dt;
    public MPacketVelocityBridge qO;
    public MCPacketPlayerBlockPlacement D3;
    public MBlocks blocks;
    public MFontRenderer R7;
    public MFreecamPlayerBridge w;
    public MInputMappings CW;
    public MVoxelShape Cr;
    public MMLGBlockWrapper Rj;
    public MCPacketPlayer_PositionRotation qq;
    public MEnchantmentHelperBridge vanillaRegistries;
    public MTileEntityChest chestTileEntity;
    public MBiomeProviderBridge K;
    public MGL11 k;
    public MFontSet fontSet;
    public MItemCameraTransformType repairable;
    public MDamageSource RK;
    public MEntity Rr;
    public MMatrix4fTransformVariantBridge Rq;
    public MGlStateManager_FogState D2;
    public MBlockReaderBridge y;
    public MTextureAtlasSpriteInfo textureAtlas;
    public MFoods foods;
    public MCPacketChatMessage RN;
    public MMappedClassSlotFp m;
    public MEnchantment RC;
    public MUtil Rf;
    public MItemCameraTransformBaseBridge hc;
    public MPlayerInput playerInputVector;
    public MTitledScreen titledScreen;
    public MCPacketPlayer_Position R5;
    public MItemAttributeModifiersComponent$Entry DN;
    public MEntityEnderPearl entityEnderPearl;
    public MInputMappingsBridge CE;
    public MObjectToIntMapEntry objectToIntMapEntry;
    public MGlStateManagerTexGenState hs;
    public MTextComponentBaseBridge mutableComponent;
    public MWorldInfo worldInfo;
    public MActiveRenderInfo hi;
    public MCPacketPlayer_Rotation Cv;
    public MFogType fogType;
    public MInventoryPlayer v;
    public MMoverType q6;
    public MAbstractBlockProperties CQ;
    public MResourceLocationKey qK;
    public MEmptyDataComponentMap emptyDataComponentMap;
    public MCPacketUseEntityAction qz;
    public MChestTypeHolder L;
    public MMainWindow DU;
    public MEntityRayTraceResult entityRayTraceResult;
    public MScore score;
    public MPotion qU;
    public MItemPotion CI;
    public MEntityLiving W;
    public MAbstractClientPlayerBridge Dk;
    public MItemAttributeModifiers itemAttributeModifiers;
    public MMatrix4fHandle D8;
    public MModelPlayer Ri;
    public MFontGlyphInfo hZ;
    public MSoundEvent Cb;
    public MRenderGlobal renderGlobal;
    public MBuiltInRegistries q7;
    public MItems projectionType;
    public MRegistryLookup holderGetterProvider;
    public MDeltaTracker deltaTracker;
    public MGlStateManagerFogStateObject glFogStateObject;
    public MRegistryAccess qs;
    public MRenderBatchFlushTarget glCommandEncoder;
    public MRenderBufferBridge Ca;
    public MVec3I vec3i;
    public MMatrixStack qn;
    public MCPacketUseEntityActionPacket h6;
    public MClientWorldInfo clientWorldInfo;
    public MPlayerEvent_NameFormat resourcePackSendPacket;
    public MGL20 RW;
    public MBoundTickingBlockEntity boundTickingBlockEntity;
    public MBiome Rm;
    public MPacketIdFactory hp;
    public MFogRenderer fogRenderer;
    public MC0BPacketEntityAction_Action DQ;
    public MEntityOtherPlayerMP entityOtherPlayer;
    public MSPacketAnimation DF;
    public MCaughtEntityActionBridge eventLoop;
    public MEnderPearlProjectileBridge enderPearlProjectileBridge;
    public MSharedMonsterAttributesBridge h3;
    public MPlayerInfo CG;
    public MStatusEffect Rb;
    public MNBTTagList I;
    public MEnumWorldBlockLayer worldBlockLayer;
    public MEmptyItemAttributeModifiers Rw;
    public MIAttributeInstance Rv;
    public MEntityClientPlayerMP q_;
    public MCPacketUseEntityOne RE;
    public MGameSettingsValue DM;
    public MEnumFacing O;
    public MRegistryNamespaced qc;
    public MMovementInput h7;
    public MLightTexture hF;
    public MGuiPlayerTabOverlay hP;
    public MSessionType sessionType;
    public MGameProfile d;
    public MEnchantmentModifierDamage enchantmentDamageModifier;
    public MKeyboardHandler CR;
    public MFontManager qb;
    public MGlStateManager_TextureState glTextureState;
    public MResourceManager packRepository;
    public MEnchantmentHelper Rk;
    public MSPacketSoundEffect Cs;
    public MCPacketUseEntityPacket Co;
    public MSPacketMapChunkBulkBridge Rg;
    public MSPacketBlockChange CN;
    public MRenderTypeBuffer c;
    public MChestType qa;
    public MRayTraceContext_BlockMode rayTraceBlockMode;
    public MDirectionBridge D5;
    public MIWorldNameable Dm;
    public MItemAttributeModifiersComponent r;
    public MIBlockState DE;
    public MMutableTextComponent RJ;
    public MResourceLocationName resourceLocationName;
    public MITooltipFlagBridge clipContextFluidMode;
    public MTeam qW;
    public MChatMessageRenderTarget chatMessageRenderTarget;
    public MScoreObjective scoreObjective;
    public MModelBiped Ct;
    public MTextureObject textureObject;
    public MStringTextComponentBridge stringTextComponentBridge;
    public MModelManager CZ;
    public MItemFood itemFood;
    public MPlayerModel Rc;
    public MEnumHandBridge hR;
    public MOrdering qm;
    public MRenderGameOverlayEvent h5;
    public MSharedMonsterAttributes qr;
    public MPlaySoundAtEntityEvent C5;
    public MBlockStateContainerBridge Ds;
    public MAbstractClientPlayer Du;
    public MSPacketEntityStatus RO;
    public MBlockReader DV;
    public MDirection Q;
    public MNonNullList nonNullList;
    public MQuaternion quaternion;
    public MSlot slot;
    public MResourceLocation resourceLocation;
    public MMaterial Cn;
    public MIInventory X;
    public MFontGlyph De;
    public MGuiContainer hK;
    public MSPacketEntity qR;
    public MScorePlayerTeam scorePlayerTeam;
    public MCPacketUseEntity Ra;
    public MEntityPlayerSP CC;
    public MShaderGroup Qv;
    public MTimer hr;
    public MMatrix4f qJ;
    public MInputMappingsInput hm;
    public MAbstractGui qQ;
    public MEvent forgeEvent;
    public MTrajectoriesItemBridge RX;
    public MItemRenderer qE;
    public MSPacketSoundEffectBridge Cj;
    public MGlStateManagerFogStateBridge q2;
    public MBlockRayTraceResult blockRayTraceResult;
    public MDataComponents q5;
    public MEquippable C3;
    public MBiomeRegistrySwitch qw;
    public MRenderBlocks renderBlocks;
    public MAxisAlignedBB RQ;
    public MMutableBoundingBox mutableBoundingBox;
    public MS08PacketPlayerPosLook q9;
    public MItemRendererBridge legacyItemCameraTransformType;
    public MEnumHand DX;
    public MGlyphInfo qp;
    public MTileEntity tileEntity;
    public MStyle qi;
    public MSharedMonsterAttributesVariantBridge D7;
    public MClickType clickType;
    public MIChunkProvider chunkProvider;
    public MRenderSystem f;
    public MGuiSpriteManager h4;
    public MSoundEventRegistryName h9;
    public MStringTextComponent Dh;
    public MItemRenderContext itemRenderContext;
    public MPlayerInteractEvent n;
    public MModelRenderer Rz;
    public MEquipmentSlotSet Ro;
    public MVisGraph visGraph;
    public MEntityFX CS;
    public MPacket packet;
    public MAtomicReferenceArrayBridge H;
    public MEffectRenderer Ru;
    public MGameSettings RM;
    public MKeyBinding hJ;
    public MTextComponentString textComponentString;
    public MItem CF;
    public MResourceKeyEnchantmentBridge enchantmentRegistryKey;
    public MRenderTypeBufferBridge framerateLimitTracker;
    public MNetHandlerPlayClient netHandlerPlayClient;
    public MEntityRenderer RY;
    public MFoodStats DJ;
    public MMethodSlotZYBridge itemBucketUse;
    public MRegistryValueBridge l;
    public MRegistry CV;
    public MEntityLivingBase hx;
    public MOpenedChestTypeSentinelBridge CD;
    public MPlayerDiggingAction Ci;
    public MEntityItem entityItem;
    public MI18n i18n;
    public MBlockPos RP;
    public MTextFormatting textFormatting;
    public MSPacketMapChunkBulk B;
    public MRenderStateBridge q3;
    public MSetVisibility setVisibility;
    public MFreecamMovementInputBridge Cc;
    public static List<Mapping> RF;
    public MDirectionVector qx;
    public MPointOfView RZ;
    public MCPacketPlayerDigging qA;
    public MCPacketEntityAction Y;
    public MFramebuffer R9;
    public MPlayerSkin playerSkin;
    public MLegacyEntityRenderPreHook legacyEntityRenderPreHook;
    public MEnumCreatureAttribute hW;
    public MMouseEvent he;
    public MGuiChat Ce;
    public MEntityPlayerMacroBridge Da;
    public MSPacketChunkDataExtracted b;
    public MGpuTextureView gpuTextureView;
    public MEntitySelectors entitySelectors;
    public MRayTraceContext Rs;
    public MChannel bakedModel;
    public MEnchantments z;
    public MRenderLivingBase CP;
    public MGameSettingsGuiScale vecDeltaCodec;
    public MSPacketHeldItemChange C6;
    public MTextureAtlasSpriteInfoBridge textureAtlasSpriteInfo;
    public MEnumCreatureAttributeBridge enumCreatureAttributeBridge;
    public MSEntityPacket qC;
    public MTextComponentTranslationBridge trackingItemStackRenderState;
    public MNetworkPlayerInfo RH;
    public MLaunchClassLoader C4;
    public MITextComponent RL;
    public MScreen screen;
    public MEntitySize h2;
    public MNetworkManager Do;
    public MItemArmor DZ;
    public MRayTraceResult C0;
    public MScoreboard scoreboard;
    public MItem_ToolMaterial Re;
    public MRenderManager CA;
    public MRegistryAccessBridge CT;
    public MEntityRayTraceBridge entityRayTraceBridge;
    public MRenderHelper x;
    public MMinecraft U;
    public MRegistrySimple hD;
    public MItemCameraTransformLeafBridge C;
    public MBytePacketFieldBridge hy;
    public MWorldProvider worldProvider;
    public MDamageSources h0;
    public MShortPacketFieldBridge F;
    public MEntityPotion entityPotion;
    public MSPacketDestroyEntities C7;
    public MSoundAwareEntityFX R4;
    public MPotionVersionRange itemEnchantments;
    public MLevelEntityGetter levelEntityGetter;
    public MSPacketDestroyEntitiesArrayBridge Rt;
    public MContainer container;
    public MGlStateManagerTexGenCoord glTexGenCoord;
    public MRender qe;
    public MNBTTagCompound Dx;
    public MClientChunkProvider Dr;
    public MItemActionResult itemActionResult;
    public MClientChatReceivedEvent qP;
    public MLanguageStateBridge S;
    public MAttributeModifier hv;
    public MTextureManager textureManager;
    public MPotionEffect C8;
    public MSPacketExplosion hQ;
    public MEnumActionResult enumActionResult;
    public MCPacketAnimation Q3;
    public MITooltipFlag creativeTabsSearch;
    public MEntityPlayer hd;
    public MGuiInventory guiInventory;
    public MItemSword qF;
    public MChunkSection Rx;
    public MNetworkManager_InboundHandlerTuplePacketListener q;
    public MVoxelShapeBridge Cl;
    public MDefaultVertexFormats DC;
    public MSPacketEntityTeleport qH;
    public MMatrixStackEntry CK;
    public MPositionMoveRotation qT;
    public MTextureAtlasSprite textureAtlasSprite;
    public MItemCameraTransformIntermediateBridge T;
    public MTextureObjectHandle gpuTexture;
    public MCPacketPlayer Dq;
    public MAbstractBlockState CJ;
    public MEntityArrow qo;
    public MHolder hN;
    public MFoodProperties foodProperties;
    public MBlock qg;
    public MItemBlock Cw;
    public MGameSettingsGuiScaleValue gameSettingsGuiScaleValue;
    public MGlyphProvider glyphSource;
    public MRenderStateBridgeVariant qX;
    public MResourceLocationConstantsBridge resourceLocationConstants;
    public MMappedFieldSingletonWrapper CL;
    public MMappedClassSlotNRegistration G;
    public MISelectionContext selectionContext;
    public MVec3d g;
    public MRenderWorldLastEvent shadersConfig;
    public MC03PacketPlayerBridge C_;
    public MTickingBlockEntity tickingBlockEntity;
    public MItemStack q8;
    public MMobSpawnerBaseLogic mobSpawnerBaseLogic;
    public MChunk qD;
    public MEntityFishHook nettyChannel;
    public MNetHandlerPlayClientImpl hB;
    public MTileEntityMobSpawner mobSpawnerTileEntity;
    public MServerData ht;
    public MRenderStateBuilder renderStateBuilder;
    public MResourceKeyHolder qV;
    public MRayTraceResult_Type rayTraceResultType;
    public MRenderItem DI;
    public MSession hw;
    public MResourceKeyRegistryLookup resourceKeyRegistryLookup;
    public MTessellator RB;
    public MResourceKey P;
    public MTextComponentTranslation D_;
    public MSPacketChunkData h8;
    public MItemTool M;
    public MSPacketEntityVelocity s;
    public MLanguage language;
    public MInventoryListBridge equipmentSlotGroup;
    public MStatusEffectSpriteUploader statusEffectSpriteUploader;
    public MItemBlockBridge hb;
    public MEnumParticleTypes Rp;
    public MBiomeRegistryName hq;
    public MGuiScreen h1;
    public MRenderPlayer renderPlayer;
    public MVector3f vector3f;
    public MMappedClassSlotZG hg;
    public MBlockHorizontal a;
    public MBlockLayerOverrideFallbackHook N;
    public MTextComponent RA;
    public MArmorMaterial e;

    public void loadMappings() {
        GuiComponent[] guiComponentArray = ForgeVersion.o();
        if (!Umbra.INSTANCE.isForgeAbsent()) {
            this.C4 = new MLaunchClassLoader();
            if (ForgeVersion.MC_1_7_10.L()) {
                this.forgeEvent = new MEvent();
                this.legacyEntityRenderPreHook = new MLegacyEntityRenderPreHook();
            }
        }
        this.U = new MMinecraft();
        this.h1 = new MGuiScreen();
        this.Ce = new MGuiChat();
        this.screen = new MScreen();
        this.hw = new MSession();
        this.RM = new MGameSettings();
        this.hJ = new MKeyBinding();
        this.Rr = new MEntity();
        this.entityItem = new MEntityItem();
        this.entityEnderPearl = new MEntityEnderPearl();
        this.hd = new MEntityPlayer();
        this.CC = new MEntityPlayerSP();
        this.hx = new MEntityLivingBase();
        this.Cy = new MWorld();
        this.ha = new MWorldClient();
        this.Rm = new MBiome();
        this.R7 = new MFontRenderer();
        this.h7 = new MMovementInput();
        this.hj = new MPlayerControllerMP();
        this.g = new MVec3d();
        this.RQ = new MAxisAlignedBB();
        this.C0 = new MRayTraceResult();
        this.RY = new MEntityRenderer();
        this.rayTraceResultType = new MRayTraceResult_Type();
        this.v = new MInventoryPlayer();
        this.q8 = new MItemStack();
        this.CI = new MItemPotion();
        this.hK = new MGuiContainer();
        this.guiInventory = new MGuiInventory();
        this.container = new MContainer();
        this.slot = new MSlot();
        this.CA = new MRenderManager();
        this.qe = new MRender();
        this.entityOtherPlayer = new MEntityOtherPlayerMP();
        this.qg = new MBlock();
        this.Qv = new MShaderGroup();
        this.blocks = new MBlocks();
        this.hB = new MNetHandlerPlayClientImpl();
        this.Q3 = new MCPacketAnimation();
        this.Y = new MCPacketEntityAction();
        this.RN = new MCPacketChatMessage();
        this.Dq = new MCPacketPlayer();
        this.Cv = new MCPacketPlayer_Rotation();
        this.R5 = new MCPacketPlayer_Position();
        this.qq = new MCPacketPlayer_PositionRotation();
        if (ForgeVersion.MC_1_21_4.d()) {
            this.C_ = new MC03PacketPlayerBridge();
        }
        this.Ck = new MCPacketHeldItemChange();
        this.RE = new MCPacketUseEntityOne();
        this.C6 = new MSPacketHeldItemChange();
        if (ForgeVersion.MC_1_17.v()) {
            this.F = new MShortPacketFieldBridge();
        }
        if (ForgeVersion.MC_1_12_2.d()) {
            this.hp = new MPacketIdFactory();
        }
        this.qU = new MPotion();
        this.C8 = new MPotionEffect();
        this.Do = new MNetworkManager();
        this.nettyChannel = new MEntityFishHook();
        this.eventLoop = new MCaughtEntityActionBridge();
        this.packet = new MPacket();
        this.q = new MNetworkManager_InboundHandlerTuplePacketListener();
        this.DI = new MRenderItem();
        this.guiChest = new MGuiChest();
        this.X = new MIInventory();
        this.hr = new MTimer();
        this.Co = new MCPacketUseEntityPacket();
        if (ForgeVersion.MC_26_1.v()) {
            this.Ra = new MCPacketUseEntity();
        }
        this.DJ = new MFoodStats();
        this.Rv = new MIAttributeInstance();
        this.hv = new MAttributeModifier();
        this.qr = new MSharedMonsterAttributes();
        this.CF = new MItem();
        this.itemBucketUse = new MMethodSlotZYBridge();
        this.renderGlobal = new MRenderGlobal();
        this.R9 = new MFramebuffer();
        this.qW = new MTeam();
        this.RL = new MITextComponent();
        this.d = new MGameProfile();
        this.tileEntity = new MTileEntity();
        if (MappedClasses.ZX != null) {
            this.RB = new MTessellator();
        }
        this.mobSpawnerTileEntity = new MTileEntityMobSpawner();
        this.mobSpawnerBaseLogic = new MMobSpawnerBaseLogic();
        this.Ri = new MModelPlayer();
        if (ForgeVersion.MC_1_21_10.v()) {
            this.DZ = new MItemArmor();
        }
        this.Rk = new MEnchantmentHelper();
        this.RC = new MEnchantment();
        this.I = new MNBTTagList();
        this.Dx = new MNBTTagCompound();
        this.qO = new MPacketVelocityBridge();
        this.s = new MSPacketEntityVelocity();
        this.hW = new MEnumCreatureAttribute();
        this.RK = new MDamageSource();
        this.x = new MRenderHelper();
        this.qC = new MSEntityPacket();
        this.netHandlerPlayClient = new MNetHandlerPlayClient();
        this.CW = new MInputMappings();
        this.textComponentString = new MTextComponentString();
        this.D_ = new MTextComponentTranslation();
        this.qi = new MStyle();
        this.qD = new MChunk();
        this.chunkProvider = new MIChunkProvider();
        this.Ct = new MModelBiped();
        this.Rz = new MModelRenderer();
        this.CP = new MRenderLivingBase();
        this.renderPlayer = new MRenderPlayer();
        this.resourceLocation = new MResourceLocation();
        this.entityPotion = new MEntityPotion();
        this.Da = new MEntityPlayerMacroBridge();
        this.qo = new MEntityArrow();
        this.h5 = new MRenderGameOverlayEvent();
        this.chestTileEntity = new MTileEntityChest();
        this.Ry = new MSPacketPlayerPosLook();
        this.Cs = new MSPacketSoundEffect();
        this.O = new MEnumFacing();
        if (ForgeVersion.c() == ForgeVersion.MC_1_8_9.i() || ForgeVersion.c() == ForgeVersion.MC_1_21_11.i()) {
            this.resourceLocationName = new MResourceLocationName();
        }
        if (ForgeVersion.c() == ForgeVersion.MC_1_21_11.i()) {
            this.qK = new MResourceLocationKey();
        }
        this.textureManager = new MTextureManager();
        this.Re = new MItem_ToolMaterial();
        this.e = new MArmorMaterial();
        this.guiContainerCreativeSlot = new MGuiContainerCreativeSlot();
        this.titledScreen = new MTitledScreen();
        this.itemFood = new MItemFood();
        this.creativeTabsSearch = new MITooltipFlag();
        this.ht = new MServerData();
        this.D2 = new MGlStateManager_FogState();
        this.Dj = new MBlockBed();
        this.C5 = new MPlaySoundAtEntityEvent();
        this.m = new MMappedClassSlotFp();
        this.Dk = new MAbstractClientPlayerBridge();
        this.scoreboard = new MScoreboard();
        this.scoreObjective = new MScoreObjective();
        this.score = new MScore();
        this.scorePlayerTeam = new MScorePlayerTeam();
        this.i18n = new MI18n();
        this.k = new MGL11();
        this.RW = new MGL20();
        this.language = new MLanguage();
        this.W = new MEntityLiving();
        this.RO = new MSPacketEntityStatus();
        this.DF = new MSPacketAnimation();
        this.qR = new MSPacketEntity();
        this.qH = new MSPacketEntityTeleport();
        this.Rt = new MSPacketDestroyEntitiesArrayBridge();
        this.D3 = new MCPacketPlayerBlockPlacement();
        this.qP = new MClientChatReceivedEvent();
        this.hy = new MBytePacketFieldBridge();
        this.textureObject = new MTextureObject();
        this.hb = new MItemBlockBridge();
        this.B = new MSPacketMapChunkBulk();
        if (GuiRenderPrimitives.V()) {
            this.Rf = new MUtil();
        }
        if (MappedClasses.ZC != null) {
            this.hs = new MGlStateManagerTexGenState();
        }
        if (MappedClasses.lO != null) {
            this.shadersConfig = new MRenderWorldLastEvent();
            Umbra.renderReady = true;
        }
        if (MappedClasses.Ym != null) {
            this.gameSettingsGuiScaleValue = new MGameSettingsGuiScaleValue();
        }
        if (ForgeVersion.MC_1_7_10.Y()) {
            this.visGraph = new MVisGraph();
            this.setVisibility = new MSetVisibility();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hE = new MBlockModelRenderer();
            }
            this.n = new MPlayerInteractEvent();
            this.hP = new MGuiPlayerTabOverlay();
            this.CN = new MSPacketBlockChange();
            this.vec3i = new MVec3I();
            this.RP = new MBlockPos();
            this.DE = new MIBlockState();
            this.Dt = new MGlStateManager();
            this.DQ = new MC0BPacketEntityAction_Action();
            this.CG = new MPlayerInfo();
            this.qZ = new MWorldRenderer();
            this.DC = new MDefaultVertexFormats();
            this.hg = new MMappedClassSlotZG();
            this.Dm = new MIWorldNameable();
            this.Rc = new MPlayerModel();
            this.Rp = new MEnumParticleTypes();
            this.Cs = new MSPacketSoundEffect();
            this.R4 = new MSoundAwareEntityFX();
            this.Rp = new MEnumParticleTypes();
            this.S = new MLanguageStateBridge();
            this.a = new MBlockHorizontal();
            this.glTextureState = new MGlStateManager_TextureState();
            this.he = new MMouseEvent();
            this.glBlendState = new MGlStateManager_BlendState();
            if (ForgeVersion.c() <= ForgeVersion.MC_1_8_9.i()) {
                this.qA = new MCPacketPlayerDigging();
            }
            this.Rx = new MChunkSection();
        } else {
            this.renderBlocks = new MRenderBlocks();
            this.q_ = new MEntityClientPlayerMP();
        }
        if (ForgeVersion.MC_1_8_9.L()) {
            this.resourcePackSendPacket = new MPlayerEvent_NameFormat();
            this.qE = new MItemRenderer();
            this.Ci = new MPlayerDiggingAction();
            this.legacyItemCameraTransformType = new MItemRendererBridge();
            this.h8 = new MSPacketChunkData();
            this.b = new MSPacketChunkDataExtracted();
            this.Rg = new MSPacketMapChunkBulkBridge();
            this.Dr = new MClientChunkProvider();
            this.worldInfo = new MWorldInfo();
        }
        if (ForgeVersion.MC_1_12_2.d()) {
            this.q6 = new MMoverType();
            this.DX = new MEnumHand();
            this.textFormatting = new MTextFormatting();
            this.clickType = new MClickType();
            this.CY = new MEntityEquipmentSlot();
            this.enumActionResult = new MEnumActionResult();
            this.nonNullList = new MNonNullList();
            this.entitySelectors = new MEntitySelectors();
        } else {
            this.Ru = new MEffectRenderer();
        }
        if (MappedClasses.Yb != null) {
            this.itemAttributeModifiers = new MItemAttributeModifiers();
            this.Rw = new MEmptyItemAttributeModifiers();
            this.lists = new MLists();
            this.qm = new MOrdering();
        }
        this.hi = new MActiveRenderInfo();
        if (ForgeVersion.MC_1_16_5.d()) {
            this.RX = new MTrajectoriesItemBridge();
            this.selectionContext = new MISelectionContext();
            this.fogRenderer = new MFogRenderer();
            this.fogType = new MFogType();
            this.qI = new MMouseHelper();
            this.RZ = new MPointOfView();
            this.hm = new MInputMappingsInput();
            this.h2 = new MEntitySize();
            this.Rj = new MMLGBlockWrapper();
            if (ForgeVersion.MC_1_20_6.v()) {
                this.hq = new MBiomeRegistryName();
            }
            this.directionAxis = new MDirectionAxis();
            this.qx = new MDirectionVector();
            this.hu = new MBlockStateWorldBridge();
            this.hF = new MLightTexture();
            this.y = new MBlockReaderBridge();
            this.RA = new MTextComponent();
            this.Dh = new MStringTextComponent();
            this.RJ = new MMutableTextComponent();
            this.Rb = new MStatusEffect();
            this.Cb = new MSoundEvent();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.statusEffectSpriteUploader = new MStatusEffectSpriteUploader();
            }
            this.textureAtlas = new MTextureAtlasSpriteInfo();
            this.textureAtlasSprite = new MTextureAtlasSprite();
            this.qn = new MMatrixStack();
            this.qJ = new MMatrix4f();
            this.CK = new MMatrixStackEntry();
            this.qQ = new MAbstractGui();
            this.vector3f = new MVector3f();
            this.Rs = new MRayTraceContext();
            this.rayTraceBlockMode = new MRayTraceContext_BlockMode();
            this.rayTraceFluidMode = new MRayTraceContext_FluidMode();
            this.Cr = new MVoxelShape();
            this.CQ = new MAbstractBlockProperties();
            this.CJ = new MAbstractBlockState();
            this.quaternion = new MQuaternion();
            this.c = new MRenderTypeBuffer();
            this.qc = new MRegistryNamespaced();
            this.CE = new MInputMappingsBridge();
            this.mutableBoundingBox = new MMutableBoundingBox();
            this.entityRayTraceResult = new MEntityRayTraceResult();
            this.Q = new MDirection();
            this.blockRayTraceResult = new MBlockRayTraceResult();
            this.f = new MRenderSystem();
            this.Ro = new MEquipmentSlotSet();
            this.clientWorldInfo = new MClientWorldInfo();
        } else {
            this.qw = new MBiomeRegistrySwitch();
            this.enchantmentDamageModifier = new MEnchantmentModifierDamage();
            if (ForgeVersion.MC_1_12_2.d()) {
                this.CD = new MOpenedChestTypeSentinelBridge();
            }
            if (ForgeVersion.MC_1_7_10.Y()) {
                this.worldBlockLayer = new MEnumWorldBlockLayer();
            }
            this.worldProvider = new MWorldProvider();
        }
        this.hD = new MRegistrySimple();
        this.N = new MBlockLayerOverrideFallbackHook();
        if (ForgeVersion.MC_1_17.d()) {
            this.D7 = new MSharedMonsterAttributesVariantBridge();
            this.h = new MEntityRemovalReason();
            if (ForgeVersion.MC_26_1.v()) {
                this.qz = new MCPacketUseEntityAction();
                this.h6 = new MCPacketUseEntityActionPacket();
            }
            this.levelEntityGetter = new MLevelEntityGetter();
            this.boundTickingBlockEntity = new MBoundTickingBlockEntity();
            this.tickingBlockEntity = new MTickingBlockEntity();
            this.Cw = new MItemBlock();
            this.H = new MAtomicReferenceArrayBridge();
            this.A = new MRenderItemContext();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.bakedModel = new MChannel();
            }
            this.Cl = new MVoxelShapeBridge();
        }
        if (ForgeVersion.MC_1_20_6.d()) {
            if (ForgeVersion.MC_1_21_10.v()) {
                this.sessionType = new MSessionType();
            }
            this.DM = new MGameSettingsValue();
            this.hQ = new MSPacketExplosion();
            this.vecDeltaCodec = new MGameSettingsGuiScale();
            this.playerSkin = new MPlayerSkin();
            this.q7 = new MBuiltInRegistries();
            this.CV = new MRegistry();
            this.hh = new MEntityEquipmentSlotHolder();
            this.q5 = new MDataComponents();
            this.hN = new MHolder();
            this.h3 = new MSharedMonsterAttributesBridge();
            this.K = new MBiomeProviderBridge();
            this.Rq = new MMatrix4fTransformVariantBridge();
            this.h9 = new MSoundEventRegistryName();
            this.P = new MResourceKey();
            this.R8 = new MTickEventPhase();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hR = new MEnumHandBridge();
            }
            this.qk = new MDataComponentMap();
            this.emptyDataComponentMap = new MEmptyDataComponentMap();
            this.itemEnchantments = new MPotionVersionRange();
            this.objectToIntMapEntry = new MObjectToIntMapEntry();
            this.CR = new MKeyboardHandler();
        } else {
            this.Cn = new MMaterial();
            this.enumCreatureAttributeBridge = new MEnumCreatureAttributeBridge();
        }
        if (ForgeVersion.MC_1_21_0.d()) {
            this.deltaTracker = new MDeltaTracker();
            if (ForgeVersion.MC_1_20_6.v()) {
                this.renderStateBuilder = new MRenderStateBuilder();
            }
            this.z = new MEnchantments();
        }
        if (ForgeVersion.MC_1_21_11.d()) {
            this.entityRayTraceBridge = new MEntityRayTraceBridge();
        }
        if (ForgeVersion.MC_1_21_4.d()) {
            this.qT = new MPositionMoveRotation();
            this.Cc = new MFreecamMovementInputBridge();
            this.projectionType = new MItems();
            this.q3 = new MRenderStateBridge();
            this.D5 = new MDirectionBridge();
            this.r = new MItemAttributeModifiersComponent();
            this.DN = new MItemAttributeModifiersComponent$Entry();
            this.C3 = new MEquippable();
            this.qV = new MResourceKeyHolder();
            this.repairable = new MItemCameraTransformType();
            this.hc = new MItemCameraTransformBaseBridge();
            this.T = new MItemCameraTransformIntermediateBridge();
            this.C = new MItemCameraTransformLeafBridge();
            this.L = new MChestTypeHolder();
            this.G = new MMappedClassSlotNRegistration();
            this.C7 = new MSPacketDestroyEntities();
            this.h0 = new MDamageSources();
            this.foods = new MFoods();
            this.foodProperties = new MFoodProperties();
            this.DV = new MBlockReader();
            this.qa = new MChestType();
            this.clipContextFluidMode = new MITooltipFlagBridge();
            this.enchantmentRegistryKey = new MResourceKeyEnchantmentBridge();
            this.qs = new MRegistryAccess();
            this.q9 = new MS08PacketPlayerPosLook();
            this.CS = new MEntityFX();
            this.RH = new MNetworkPlayerInfo();
        }
        if (ForgeVersion.MC_1_21_6.d()) {
            this.playerInputVector = new MPlayerInput();
            this.Ca = new MRenderBufferBridge();
            if (ForgeVersion.MC_26_1.d()) {
                this.Ds = new MBlockStateContainerBridge();
            }
            this.glCommandEncoder = new MRenderBatchFlushTarget();
            this.equipmentSlotGroup = new MInventoryListBridge();
            this.CL = new MMappedFieldSingletonWrapper();
            this.gpuTexture = new MTextureObjectHandle();
            this.h4 = new MGuiSpriteManager();
            this.D8 = new MMatrix4fHandle();
            this.glFogStateObject = new MGlStateManagerFogStateObject();
            this.q2 = new MGlStateManagerFogStateBridge();
            this.stringTextComponentBridge = new MStringTextComponentBridge();
            this.trackingItemStackRenderState = new MTextComponentTranslationBridge();
            this.DU = new MMainWindow();
        } else {
            this.M = new MItemTool();
            this.qF = new MItemSword();
        }
        if (ForgeVersion.MC_1_21_10.d()) {
            this.CZ = new MModelManager();
            this.resourceLocationConstants = new MResourceLocationConstantsBridge();
            this.w = new MFreecamPlayerBridge();
            this.textureAtlasSpriteInfo = new MTextureAtlasSpriteInfoBridge();
            this.Du = new MAbstractClientPlayer();
            this.renderTarget = new MTextureManagerHandle();
            this.hZ = new MFontGlyphInfo();
            this.gpuTextureView = new MGpuTextureView();
            this.De = new MFontGlyph();
            this.qp = new MGlyphInfo();
            this.fontSet = new MFontSet();
            this.qb = new MFontManager();
            this.glyphSource = new MGlyphProvider();
            this.framerateLimitTracker = new MRenderTypeBufferBridge();
            this.packRepository = new MResourceManager();
        }
        this.enderPearlProjectileBridge = new MEnderPearlProjectileBridge();
        if (ForgeVersion.MC_1_20_6.d()) {
            this.chatMessageRenderTarget = new MChatMessageRenderTarget();
            this.mutableComponent = new MTextComponentBaseBridge();
            this.vanillaRegistries = new MEnchantmentHelperBridge();
            this.R2 = new MResourceKeyRegistryLookupStreamBridge();
            this.CT = new MRegistryAccessBridge();
            this.l = new MRegistryValueBridge();
            this.Cj = new MSPacketSoundEffectBridge();
            this.qX = new MRenderStateBridgeVariant();
            this.holderGetterProvider = new MRegistryLookup();
            this.resourceKeyRegistryLookup = new MResourceKeyRegistryLookup();
        }
        if (ForgeVersion.MC_1_21_4.d()) {
            this.glTexGenCoord = new MGlStateManagerTexGenCoord();
            this.itemRenderContext = new MItemRenderContext();
            this.itemActionResult = new MItemActionResult();
        }
    }

    public static void j(int n) {
        DH = n;
    }

    static {
        RF = new ArrayList<Mapping>();
        Mapper.j(34);
    }

    public static int D() {
        int n = Mapper.u();
        return 0;
    }


    public static int u() {
        return DH;
    }
}

